on:
  workflow_dispatch:

jobs:
  deploy_dev:
    environment:
      name: 'dev'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: mongosh "mongodb+srv://cluster0.xzkla.mongodb.net/sample_training" --username testUser --password testUser --file ./deployment-scripts/release-1.0.js
      shell: bash
  deploy_qa:
    needs: [deploy_dev]
    environment:
      name: 'qa'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: mongosh "mongodb+srv://cluster0.xzkla.mongodb.net/sample_training" --username testUser --password testUser --file ./deployment-scripts/release-1.0.js
      shell: bash
  deploy_stage:
    needs: [deploy_qa]
    environment:
      name: 'staging'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: mongosh "mongodb+srv://cluster0.xzkla.mongodb.net/sample_training" --username testUser --password testUser --file ./deployment-scripts/release-1.0.js
      shell: bash
  deploy_prod:
    needs: [deploy_stage]
    environment:
      name: 'prod'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: mongosh "mongodb+srv://cluster0.xzkla.mongodb.net/sample_training" --username testUser --password testUser --file ./deployment-scripts/release-1.0.js
      shell: bash
